version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: |
            apt-get update
            yes "" | apt-get --yes install software-properties-common
            add-apt-repository ppa:ubuntu-toolchain-r/test
            apt-get update
            apt-get --yes install g++-7
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install gtest
          command: 'apt-get update && sudo apt-get install -y libgtest-dev'
      - run:
          name: Install Python3
          command: 'apt-get update && sudo apt-get install -y python3 python3-pip'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Point Unit Testing
          command: './test/cpp/runAllPyllarsTest'
      - run:
          name: Python tests
          command:  |
            cd test/python && pytest -s test_basics.py

