version: 2

jobs:
  build:
    docker:
      - image: "circleci/buildpack-deps:bionic"
    steps:
      - checkout
      - run:
          name: Installing GCC
          command: |
            sudo apt-get update
            sudo apt-get --yes install g++-7
      - run:
          name: Install CMAKE
          command: 'sudo apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install clang tools
          command: 'sudo apt-get update && sudo apt-get install -y clang-tools-5.0'
      - run:
          name: Install gtest
          command: 'sudo apt-get update && sudo apt-get install -y libgtest-dev'
      - run:
          name: Install Python3
          command: |
            suudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
            sudo apt-get update && sudo apt-get install -y python3.7-dev python3,7-pip
      - run:
          name: Install pytest
          command: 'sudo pip3 install pytest ply dataclasses'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build -- -j 4'
      - run:
          name: Point Unit Testing
          command: |
            ./build/test/cpp/runAllPyllarsTest
      - run:
          name: Python tests
          command:  |
            PYTHONPATH=./src/python/ pytest -s ./test/python/test_basics.py

